name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13.12.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.12.0
      - name: Install all node depedencies
        run: npm install
      - name: Install grunt
        run: npm install -g grunt-cli
      - name: Grunt build
        run: grunt build
      - uses: actions/upload-artifact@v1
        with:
          name: website-source
          path: out/
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'out'

